[M5Stack_Cardputer_ADV]
extends = esp32_base
board = m5stack-stamps3
build_flags =
  ${esp32_base.build_flags}
  -I variants/m5stack_cardputer_adv
  -D CARDPUTER_ADV
  -D ARDUINO_USB_CDC_ON_BOOT=1
  ;---LoRa
  -D P_LORA_DIO_1=4 ;IRQ
  -D P_LORA_NSS=5
  -D P_LORA_RESET=3
  -D P_LORA_BUSY=6
  -D P_LORA_SCLK=40
  -D P_LORA_MISO=39
  -D P_LORA_MOSI=14
  -D SX126X_DIO2_AS_RF_SWITCH=true
  -D SX126X_DIO3_TCXO_VOLTAGE=1.8
  -D SX126X_CURRENT_LIMIT=140
  -D USE_SX1262
  -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D LORA_TX_POWER=22
  -D SX126X_RX_BOOSTED_GAIN=1
  ;--BATTERY
  -D PIN_VBAT_READ=10
  -D PIN_USER_BTN=0
  ;---I2C
  -D PIN_BOARD_SDA=8  ;14pin header & TCA8418
  -D PIN_BOARD_SCL=9  ;14pin header & TCA8418
  -D PIN_BOARD_SDA1=2 ;grove
  -D PIN_BOARD_SCL1=1 ;grove
  ;---GPS
  -D ENV_INCLUDE_GPS=1
  -D PIN_GPS_RX=13
  -D PIN_GPS_TX=15
  -D GPS_BAUD_RATE=115200
  ;---LCD
  -D PIN_TFT_SCL=36
  -D PIN_TFT_SDA=35
  -D PIN_TFT_RST=33
  -D PIN_TFT_VDD_CTL=38
  -D PIN_TFT_LEDA_CTL=38
  -D PIN_TFT_LEDA_CTL_ACTIVE=HIGH
  -D PIN_TFT_CS=37
  -D PIN_TFT_DC=34 ;RS
  -D ST7789
  -D DISPLAY_CLASS=ST7789Display
  ;---TCA8418
  -D ENV_USE_TCA8418=1
build_src_filter = ${esp32_base.build_src_filter}
  +<../variants/m5stack_cardputer_adv>
  +<helpers/sensors/*.cpp>
  +<helpers/ui/ST7789Display.cpp>
  +<helpers/ui/OLEDDisplay.cpp>
  +<helpers/ui/OLEDDisplayFonts.cpp>
lib_deps =
  ${esp32_base.lib_deps}
  ${sensor_base.lib_deps}
  adafruit/Adafruit ST7735 and ST7789 Library @ ^1.11.0

[env:M5Stack_Cardputer_ADV_companion_radio_ble]
extends = M5Stack_Cardputer_ADV
build_flags =
  ${M5Stack_Cardputer_ADV.build_flags}
  -I examples/companion_radio/ui-new
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D BLE_PIN_CODE=123456
  -D BLE_DEBUG_LOGGING=1
  -D OFFLINE_QUEUE_SIZE=256
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
build_src_filter = ${M5Stack_Cardputer_ADV.build_src_filter}
  +<helpers/esp32/*.cpp>
  +<helpers/ui/MomentaryButton.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
lib_deps =
  ${M5Stack_Cardputer_ADV.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:M5Stack_Cardputer_ADV_companion_radio_usb]
extends = M5Stack_Cardputer_ADV
build_flags =
  ${M5Stack_Cardputer_ADV.build_flags}
  -I examples/companion_radio/ui-new
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
; NOTE: DO NOT ENABLE -->  -D MESH_PACKET_LOGGING=1
; NOTE: DO NOT ENABLE -->  -D MESH_DEBUG=1
build_src_filter = ${M5Stack_Cardputer_ADV.build_src_filter}
  +<helpers/ui/MomentaryButton.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
lib_deps =
  ${M5Stack_Cardputer_ADV.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:M5Stack_Cardputer_ADV_repeater]
extends = M5Stack_Cardputer_ADV
build_flags =
  ${M5Stack_Cardputer_ADV.build_flags}
  -D ADVERT_NAME='"Cardputer_adv Repeater"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
build_src_filter = ${M5Stack_Cardputer_ADV.build_src_filter}
  +<../examples/simple_repeater>
lib_deps =
  ${M5Stack_Cardputer_ADV.lib_deps}
  ${esp32_ota.lib_deps}

[env:M5Stack_Cardputer_ADV_repeater_bridge_espnow]
extends = M5Stack_Cardputer_ADV
build_flags =
  ${M5Stack_Cardputer_ADV.build_flags}
  -D ADVERT_NAME='"ESPNow Bridge"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
  -D WITH_ESPNOW_BRIDGE=1
;  -D BRIDGE_DEBUG=1
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
build_src_filter = ${M5Stack_Cardputer_ADV.build_src_filter}
  +<helpers/bridges/ESPNowBridge.cpp>
  +<../examples/simple_repeater>
lib_deps =
  ${M5Stack_Cardputer_ADV.lib_deps}
  ${esp32_ota.lib_deps}

[env:M5Stack_Cardputer_ADV_terminal_chat]
extends = M5Stack_Cardputer_ADV
build_flags =
  ${M5Stack_Cardputer_ADV.build_flags}
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=1
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
build_src_filter = ${M5Stack_Cardputer_ADV.build_src_filter}
  +<../examples/simple_secure_chat/main.cpp>
lib_deps =
  ${M5Stack_Cardputer_ADV.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:M5Stack_Cardputer_ADV_room_server]
extends = M5Stack_Cardputer_ADV
build_flags =
  ${M5Stack_Cardputer_ADV.build_flags}
  -D ADVERT_NAME='"Cardputer_adv Room"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D ROOM_PASSWORD='"hello"'
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
build_src_filter = ${M5Stack_Cardputer_ADV.build_src_filter}
  +<../examples/simple_room_server>
lib_deps =
  ${M5Stack_Cardputer_ADV.lib_deps}
  ${esp32_ota.lib_deps}

[env:M5Stack_Cardputer_ADV_kiss_modem]
extends = M5Stack_Cardputer_ADV
build_src_filter = ${M5Stack_Cardputer_ADV.build_src_filter}
  +<../examples/kiss_modem/>
